# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_yuhun_ocr(object):
    def setupUi(self, yuhun_ocr):
        yuhun_ocr.setObjectName("yuhun_ocr")
        yuhun_ocr.setWindowModality(QtCore.Qt.NonModal)
        yuhun_ocr.resize(550, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(yuhun_ocr.sizePolicy().hasHeightForWidth())
        yuhun_ocr.setSizePolicy(sizePolicy)
        yuhun_ocr.setMinimumSize(QtCore.QSize(550, 350))
        yuhun_ocr.setMaximumSize(QtCore.QSize(550, 350))
        self.centralwidget = QtWidgets.QWidget(yuhun_ocr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.panel_left = QtWidgets.QWidget(self.centralwidget)
        self.panel_left.setObjectName("panel_left")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.panel_left)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(self.panel_left)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setObjectName("gridLayout")
        self.bt_1 = QtWidgets.QPushButton(self.widget_3)
        self.bt_1.setObjectName("bt_1")
        self.gridLayout.addWidget(self.bt_1, 0, 0, 1, 1)
        self.bt_2 = QtWidgets.QPushButton(self.widget_3)
        self.bt_2.setObjectName("bt_2")
        self.gridLayout.addWidget(self.bt_2, 0, 1, 1, 1)
        self.bt_3 = QtWidgets.QPushButton(self.widget_3)
        self.bt_3.setObjectName("bt_3")
        self.gridLayout.addWidget(self.bt_3, 1, 0, 1, 1)
        self.bt_4 = QtWidgets.QPushButton(self.widget_3)
        self.bt_4.setObjectName("bt_4")
        self.gridLayout.addWidget(self.bt_4, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.panel_left)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.yuhun_select = QtWidgets.QComboBox(self.widget_4)
        self.yuhun_select.setObjectName("yuhun_select")
        self.gridLayout_3.addWidget(self.yuhun_select, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.position_select = QtWidgets.QComboBox(self.widget_4)
        self.position_select.setObjectName("position_select")
        self.gridLayout_3.addWidget(self.position_select, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.panel_left)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ocr_bt = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ocr_bt.sizePolicy().hasHeightForWidth())
        self.ocr_bt.setSizePolicy(sizePolicy)
        self.ocr_bt.setObjectName("ocr_bt")
        self.horizontalLayout_2.addWidget(self.ocr_bt)
        self.inquire_bt = QtWidgets.QPushButton(self.widget_5)
        self.inquire_bt.setObjectName("inquire_bt")
        self.horizontalLayout_2.addWidget(self.inquire_bt)
        self.verticalLayout_4.addWidget(self.widget_5)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.panel_left)
        self.panel_right = QtWidgets.QWidget(self.centralwidget)
        self.panel_right.setObjectName("panel_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panel_right)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.panel_right)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.panel_right)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.panel_right)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        yuhun_ocr.setCentralWidget(self.centralwidget)

        self.retranslateUi(yuhun_ocr)
        QtCore.QMetaObject.connectSlotsByName(yuhun_ocr)

    def retranslateUi(self, yuhun_ocr):
        _translate = QtCore.QCoreApplication.translate
        yuhun_ocr.setWindowTitle(_translate("yuhun_ocr", "御魂识别器"))
        self.bt_1.setText(_translate("yuhun_ocr", "导入御魂"))
        self.bt_2.setText(_translate("yuhun_ocr", "导出json"))
        self.bt_3.setText(_translate("yuhun_ocr", "导出xls"))
        self.bt_4.setText(_translate("yuhun_ocr", "导出txt"))
        self.label_2.setText(_translate("yuhun_ocr", "御魂位置"))
        self.label.setText(_translate("yuhun_ocr", "御魂类别"))
        self.ocr_bt.setText(_translate("yuhun_ocr", "开始识别"))
        self.inquire_bt.setText(_translate("yuhun_ocr", "查看御魂"))
        self.textBrowser.setHtml(_translate("yuhun_ocr", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("yuhun_ocr", "By-火电太热"))

